#!/bin/zsh

echo '#====================#'
echo '# Rebase Repository  #'
echo '#====================#'
git stash clear
git stash
git pull --rebase

echo ''
echo '#====================#'
echo '# Replace Rcfiles    #'
echo '#====================#'
rm -f ~/.gitconfig && ln -s `pwd`/gitconfig ~/.gitconfig && echo 'o -> ~/.gitconfig'
rm -f ~/.gitignore && ln -s `pwd`/gitignore ~/.gitignore && echo 'o -> ~/.gitignore'
rm -f ~/.screenrc  && ln -s `pwd`/screenrc  ~/.screenrc  && echo 'o -> ~/.screenrc'
rm -f ~/.vim       && ln -s `pwd`/vim       ~/.vim       && echo 'o -> ~/.vim/'
rm -f ~/.vimrc     && ln -s `pwd`/vimrc     ~/.vimrc     && echo 'o -> ~/.vimrc'
rm -f ~/.zshrc     && ln -s `pwd`/zshrc     ~/.zshrc     && echo 'o -> ~/.zshrc'
rm -f ~/.gemrc     && ln -s `pwd`/gemrc     ~/.gemrc     && echo 'o -> ~/.gemrc'


echo ''
echo '#====================#'
echo '# Update submodules  #'
echo '#====================#'
git submodule init
git submodule update
git submodule foreach 'git pull origin master'

echo ''
echo '#=====================#'
echo '# Install Vim Bundles #'
echo '#=====================#'
echo 'Vundle: Installing bundles...'
echo ':BundleInstall' | vim > /dev/null 2>&1
echo 'Vundle: Cleaning bundles...'
echo ':BundleClean'   | vim > /dev/null 2>&1

echo ''
echo '#=====================#'
echo '# Retouch Alters      #'
echo '#=====================#'
git stash pop

echo ''
echo '#=====================#'
echo '# Upgrade Done        #'
echo '#=====================#'
echo ''
